#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf processor*
rm -rf constant/polyMesh
rm -rf postProcessing
rm -f log*
rm -r 0

cleanCase

# ----------------------------------------------------------------- end-of-file
